# Generated by Django 2.2 on 2020-06-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='registration_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='nric',
            field=models.CharField(default='NA', max_length=12),
        ),
    ]
