# Generated by Django 2.2 on 2020-06-07 03:00

import core.helpers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=100)),
                ('email', models.CharField(default='NA', max_length=100)),
                ('phone', models.CharField(default='NA', max_length=100)),
                ('complaint', models.TextField(default='NA')),
                ('complaint_category', models.CharField(choices=[('TX', 'Text'), ('VB', 'Verbal'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('supporting_docs', models.FileField(null=True, upload_to=core.helpers.PathAndRename('docs'))),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(default='NA', max_length=100)),
                ('category', models.CharField(choices=[('IN', 'Internal'), ('EX', 'External'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('survey_type', models.CharField(choices=[('SR', 'Star Rating'), ('MC', 'Multiple Choice'), ('FT', 'Free Text'), ('NS', 'Net Promoter Score'), ('TU', 'Thums Up/Down'), ('EM', 'Emoji'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer', models.CharField(default='NA', max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_answer_by', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbacks.SurveyQuestion')),
            ],
        ),
    ]
