# Generated by Django 2.2 on 2020-06-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_auto_20200607_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='user_type',
            field=models.CharField(choices=[('AD', 'Admin'), ('US', 'User')], default='US', max_length=2),
        ),
    ]
