# Generated by Django 2.2 on 2020-06-08 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_organisation_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='user_type',
        ),
    ]
